+incdir+../../src/globals/
+incdir+../../src/hvl_top/test/sequences/master_sequences/
+incdir+../../src/hvl_top/master/
+incdir+../../src/hdl_top/master_agent_bfm/ 
+incdir+../../src/hvl_top/env/virtual_sequencer/
+incdir+../../src/hvl_top/test/virtual_sequences/
+incdir+../../src/hvl_top/env
+incdir+../../src/hvl_top/slave
+incdir+../../src/hvl_top/test/sequences/slave_sequences/
+incdir+../../src/hvl_top/test
+incdir+../../src/hdl_top/slave_agent_bfm
+incdir+../../src/hdl_top/i2c_interface
../../src/globals/i2c_globals_pkg.sv
../../src/hvl_top/master/i2c_master_pkg.sv
../../src/hvl_top/slave/i2c_slave_pkg.sv
../../src/hvl_top/test/sequences/master_sequences/i2c_master_seq_pkg.sv
../../src/hvl_top/test/sequences/slave_sequences/i2c_slave_seq_pkg.sv
../../src/hvl_top/env/i2c_env_pkg.sv
../../src/hvl_top/test/virtual_sequences/i2c_virtual_seq_pkg.sv
../../src/hvl_top/test/i2c_test_pkg.sv
../../src/hdl_top/i2c_interface/i2c_if.sv
../../src/hdl_top/master_agent_bfm/i2c_master_driver_bfm.sv
../../src/hdl_top/master_agent_bfm/i2c_master_monitor_bfm.sv
../../src/hdl_top/master_agent_bfm/i2c_master_agent_bfm.sv
../../src/hdl_top/slave_agent_bfm/i2c_slave_driver_bfm.sv
../../src/hdl_top/slave_agent_bfm/i2c_slave_monitor_bfm.sv
../../src/hdl_top/slave_agent_bfm/i2c_slave_agent_bfm.sv
../../src/hdl_top/hdl_top.sv
../../src/hvl_top/hvl_top.sv 
